all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: ./venv/bin/python3
      ansible_become_user: root
      ansible_become_password: vanson1997
      hostname: vdt-23
  children:
    nodes:
      hosts:
        node1:
          ansible_ssh_host: 3.27.152.18
          ansible_ssh_user: ubuntu
          ansible_ssh_private_key_file: ~/Desktop/vdt-2023.pem
        node2:
          ansible_ssh_host: 192.168.1.100
          ansible_ssh_user: ubuntu
          ansible_ssh_private_key_file: ~/Desktop/node2-key.pem
