---
- name: Setup Docker
  hosts: all
  become: true
  gather_facts: true
  roles:
  - common

- name: Deploy the application on remote machines
  hosts: nodes
  become: true
  gather_facts: true
  roles:
  - db
  - api
  - web

- name: Monitoring
  hosts: localhost
  become: true
  gather_facts: true
  roles:
  - monitoring
  
