version: '3.3'

services:
  db:
    image: mongo:5.0.17
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_DATABASE: flask
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | db db:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  web:
    build: ./web
    container_name: flask
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: flask
      MONGODB_HOSTNAME: db
    ports:
      - "5000:5000"
    depends_on:
      - db
  nginx:
    image: nginx:1.22.1-alpine3.17-slim
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web